name: "Deploy vite app"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  just_echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo here
        run: echo "Hell world !"
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Mail server address (Gmail SMTP server)
          server_address: smtp.gmail.com
          # Server port for secure connection (Gmail uses 465 for SSL/TLS)
          server_port: 465
          # Secure connection (true for SSL/TLS)
          secure: true
          # Your Gmail username (stored in GitHub Secrets)
          username: ${{ secrets.SMTP_USERNAME }}
          # Your Gmail App Password (stored in GitHub Secrets)
          password: ${{ secrets.SMTP_PASSWORD }}
          # Email subject
          subject: "Github Actions job result"
          # Recipients' email addresses (comma-separated)
          to: "raktsarthi@gmail.com"
          # Sender's name (and optionally address)
          from: "jugalsuthar2004@gmail.com"
          # Plain text body of the email
          body: "Build job of ${{ github.repository }} completed successfully!"
          # Optional: HTML body of the email (e.g., from a file)
          # html_body: file://README.html
          # Optional: Carbon copy (CC) recipients
          # cc: kyloren@example.com,leia@example.com
          # Optional: Blind carbon copy (BCC) recipients
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional: Priority of the email ('high', 'normal', 'low')
          priority: normal
          # Optional: Attachments (e.g., files generated by the workflow)
          # attachments: attachments.zip,git.diff,./dist/static/*.js
